# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeliveryApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeliveryApp

  target 'DeliveryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeliveryAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DeliveryApp WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeliveryApp WatchKit App

end

target 'DeliveryApp WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeliveryApp WatchKit Extension

end
