# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'DBAV_Example' do
    
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for DBAV_Example
    
    # Networking
    pod 'Alamofire'
    
    # JSON and XML
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'SWXMLHash', '~> 2.4.0'
    pod 'AEXML'
    
    # Localization
    pod 'PolyglotLocalization'
    
    # User Interface
    pod 'ActionSheetPicker-3.0'
    pod 'TPKeyboardAvoiding'
    pod 'KVNProgress'
    pod 'Kingfisher'
    
    # Security
    pod 'CryptoSwift'
    
    target 'DBAV_ExampleTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'DBAV_ExampleUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
