# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DBAV_Example' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DBAV_Example
  pod 'Alamofire'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'PolyglotLocalization'
  pod 'TPKeyboardAvoiding'
  pod 'KVNProgress'
  pod 'Kingfisher'

  target 'DBAV_ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DBAV_ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
